// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../node_modules/bs-platform/lib/es6/list.js";

var length = List.length;

function pushTerm(x, g, ctx) {
  return {
          hd: [
            x,
            g
          ],
          tl: ctx
        };
}

function popTerm(ctx) {
  if (ctx) {
    return ctx.tl;
  } else {
    return /* [] */0;
  }
}

function newVar(i, alias) {
  return {
          TAG: /* Var */0,
          _0: i,
          _1: alias
        };
}

function newAbs(t, x, alias) {
  return {
          TAG: /* Abs */1,
          _0: t,
          _1: x,
          _2: alias
        };
}

function newApp(t1, t2, alias) {
  return {
          TAG: /* App */2,
          _0: t1,
          _1: t2,
          _2: alias
        };
}

function prettyPrint(t, x) {
  switch (t.TAG | 0) {
    case /* Var */0 :
        return String(t._0);
    case /* Abs */1 :
        var t$1 = t._0;
        if (x === 0) {
          return "λ " + prettyPrint(t$1, 0);
        } else {
          return "(λ " + prettyPrint(t$1, 0) + ")";
        }
    case /* App */2 :
        var t2 = t._1;
        var t1 = t._0;
        if (x !== 0) {
          return "(" + prettyPrint(t1, x) + " " + prettyPrint(t2, x + 1 | 0) + ")";
        }
        switch (t1.TAG | 0) {
          case /* Abs */1 :
              return prettyPrint(t1, 1) + " " + prettyPrint(t2, 1);
          case /* Var */0 :
          case /* App */2 :
              break;
          
        }
        return prettyPrint(t1, 0) + " " + prettyPrint(t2, 1);
        break;
    
  }
}

export {
  length ,
  pushTerm ,
  popTerm ,
  newVar ,
  newAbs ,
  newApp ,
  prettyPrint ,
  
}
/* No side effect */
